[package]
name = "pcsclite-sys"
version = "0.1.0"
authors = ["Thomas Kerber <thomas@tkerber.org>"]
links = "pcsclite"
build = "build.rs"

[dependencies]
libc = "0.2"

[build-dependencies]
pkg-config = "0.3"
